spring:
  profiles:
    active: dev

server:
  port: 9090

mybatis:
  mapperLocations: classpath*:Mapper/*Mapper.xml
  configuration:
      mapUnderscoreToCamelCase: true
      cache-enabled: true

application:
  name: cool-boot