spring:
  datasource:
      url: jdbc:mysql://47.52.195.163:3306/wuai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: tengjunjiesb

jdbc:
  url: jdbc:mysql://106.15.205.155:3306/wuai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
  user: root
  pass: xltys1995

rabbit:
  host: 106.15.205.155
  name: guest
  pass: guest

redis:
  host: 120.55.67.48
  port: 8048
  database: 1
  password: nessary

tcp:
  port: 5005

logging:
  config: classpath:logback-spring.xml
  path: C:\Users\Administrator\Desktop\mylog

demo:
  queue:  cool.dev.queue.demo
  exchange: cool.dev.exchange.demo
  routingKey: cool.dev.routingKey.demo

task:
  queue:  cool.dev.queue.task
  exchange: cool.dev.exchange.task
  routingKey: cool.dev.routingKey.task



